version: '3.7'
services:
    api-gateway:
        build: api-gateway/
        container_name: api-gateway
        ports: 
            - '80:80'
            - '443:443'
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
            - ./data/logs/nginx:/var/log/nginx
        secrets:
            - api_keys
    
    certbot:
        image: certbot/certbot
        container_name: certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${1}; done'"
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www/:/var/www/certbot
   
    py-mongo-api:
        build: py-mongo-api/
        container_name: py-mongo-api
        environment:
            - PYTHONUNBUFFERED=1
            - MONGO_USERNAME=/run/secrets/speedtest-db_api_username
            - MONGO_PASSWORD=/run/secrets/speedtest-db_api_password
            - ROUTE_CONFIG=api
        entrypoint:
            - gunicorn
            - --bind
            - 0.0.0.0:5000
            - wsgi:app
        secrets:
            - speedtest-db_api_username
            - speedtest-db_api_password
            - api_keys

    py-mongo-web:
        build: py-mongo-api/
        container_name: py-mongo-web
        environment:
            - PYTHONUNBUFFERED=1
            - MONGO_USERNAME=/run/secrets/speedtest-db_api_username
            - MONGO_PASSWORD=/run/secrets/speedtest-db_api_password
            - ROUTE_CONFIG=web
        entrypoint:
            - gunicorn
            - --bind
            - 0.0.0.0:5000
            - wsgi:app
        secrets:
            - speedtest-db_api_username
            - speedtest-db_api_password
            - api_keys
    
    speedtest-db:
        image: mongo
        container_name: speedtest-db
        environment:
            - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/speedtest-db_root_username
            - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/speedtest-db_root_password
            - MONGO_INITDB_DATABASE=speedtest
            - MONGO_INITDB_USERNAME=/run/secrets/speedtest-db_api_username
            - MONGO_INITDB_PASSWORD=/run/secrets/speedtest-db_api_password
        volumes:
            - ./data/db/speedtest/:/data/db/
            - ./speedtest-db/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
        secrets:
            - speedtest-db_root_username
            - speedtest-db_root_password
            - speedtest-db_api_username
            - speedtest-db_api_password

secrets:
    speedtest-db_root_username:
        file: ./data/secrets/speedtest-db_root_username
    speedtest-db_root_password:
        file: ./data/secrets/speedtest-db_root_password
    speedtest-db_api_username:
        file: ./data/secrets/speedtest-db_api_username
    speedtest-db_api_password:
        file: ./data/secrets/speedtest-db_api_password
    api_keys:
        file: ./data/secrets/api_keys
