version: '3.7'
services:
    web-main:
        build: web-main/
        container_name: web-admin
    api-gateway:
        build: api-gateway/
        container_name: api-gateway
        ports: 
            - '80:80'
            - '443:443'
        command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
    certbot:
        image: certbot/certbot
        container_name: certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${1}; done'"
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www/:/var/www/certbot
    py-mongo-api:
        build: py-mongo-api/
        container_name: py-mongo-api
